apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config-map
  labels:
      {{- include "todo-list.labels" . | nindent 4 }}
data:
  config.js: |
    window.RUNTIME_CONFIG = {
      URL_V1: "{{ .Values.environmentVars.URL_V1 }}",
      URL_V2: "{{ .Values.environmentVars.URL_V2 }}"
    };
