apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-list.fullname" . }}
  labels:
    {{- include "todo-list.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "todo-list.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo-list.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-todo-list-config-map
