apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-list
  labels:
    {{- include "todo-list.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "todo-list.selectorLabels" . | nindent 4 }}
