FROM python:3.9-slim

WORKDIR /app

COPY fetchData/requirements.txt fetchData/init.py fetchData/utils/ .
RUN pip install --no-cache-dir -r fetchData/requirements.txt

COPY . .

CMD ["python3", "init.py"]
